### ISSUE TITLE
ccf_part relationships between cell types and classifications between anatomical structures and cell types

### ISSUE THREAD

**Issue by dosumis** [hubmapconsortium/ccf-validation-tools#302]
Does this reflect oddities in the ASCT+B table? 
![image](https://github.com/hubmapconsortium/ccf-validation-tools/assets/112839/3b014ba6-a925-4448-9bad-5fb8b53665e2)
CL terms in AS slots and Uberon terms in CT slots.  If so, shouldn't some basic validation of sheet catch this?

**Comment by aleixpuigb** [comment]
There are no CL terms in CT slots:
- retina is in the las AS slot
- neuron is CT1
- microglial cell is CT2

@anitacaron can correct me if I'm wrong, but since in the eye table CT1 slots are very general (neuron, epithelial cell, ...), they don't validate with the last AS slot, but CT2 does (and with CT1). That's why it has these two relationships.

**Comment by anitacaron** [comment]
@dosumis The `rdfs:subClassOf` label is not between microglial cell and neuron, but another arrow passing by.

**Comment by anitacaron** [comment]
The `ccf_part_of` and `ccf_located_in` are default relationships to show not valid ones and only added in the graph, not in the CCF_CT_AS.owl.
